import { Roboto, Tangerine, Italianno } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const roboto = Roboto({ subsets: ["latin"], weight: "400" });
export const italianno = Italianno({ subsets: ["latin"], weight: "400" });
export const tangerine = Tangerine({subsets: ["latin"], weight: "700"});

export const metadata = {
  title: "Swift",
  description: "Generated by create next app",
  icons: {
    icon: "http://localhost:8080/icon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} bg-gray-100 h-screen overflow-auto scrollbar-thumb-purple-500 scrollbar-track-gray-300 scrollbar-thin`}
      >
        <Navbar />
        <div className="px-5 pt-3">{children}</div>
      </body>
    </html>
  );
}
