
import { roboto } from "./fonts";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata = {
    title: {
        template: "%s | Swift",
        default: "Swift"
    },
    description: "Generated by create next app",
    icons: {
        icon: "http://localhost:8080/icon.png",
    },
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${roboto.className} bg-white min-h-screen antialiased flex flex-col overflow-auto scrollbar-thumb-purple-500 scrollbar-track-gray-300 scrollbar-thin`}
            >
                <Navbar />
                <main className="flex-grow">
                    {children}
                </main>

                    <Footer />
            </body>
        </html>
    );
};
